version: '3.9'

services:
  web:
    build:
      context: . 
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_web
    command: /start.sh
    volumes:
      - .:/two
    ports:
      - 8000:8080
      - 8091:443
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db


  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
  
  redis:
    image: redis:7-alpine
  
  celery_worker:
    build: 
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/two
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/two
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db
      - redis
  
  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_flower
    command: /start-flower.sh
    volumes:
      - .:/two
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data: