services:
  web:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: backend5_web
    command: /start.sh
    ports:
      - 8080:8080
      - 8091:443
    volumes:
      - .:/five
    env_file:
      ./.env/.dev-sample
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:14-alpine
    volumes:
      - postgres5_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
  
  redis:
    image: redis:7-alpine
  
  celery_worker:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: backend5_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/five
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile 
    image: backend5_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/five
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  
  flower:
    build:
      context: . 
      dockerfile: compose/local/django/Dockerfile
    image: backend5_flower
    command: /start-flower.sh
    volumes:
      - .:/five
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres5_data: