version: '3.8'

services:
  web:
    build:
      context: . 
      dockerfile: compose/local/django/Dockerfile
    image: backend_web
    command: /start.sh
    volumes:
      - .:/four
    ports:
      - 8000:8000
      - 8091:443
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  db:
    image: postgres:14-alpine 
    volumes:
      - postgres4_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=hello_django
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
  
  redis:
    image: redis:7-alpine
  
  celery_worker:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: backend_celery_worker
    command: /start-celeryworker.sh
    volumes:
      - .:/four
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
  
  celery_beat:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: backend_celery_beat
    command: /start-celerybeat.sh
    volumes:
      - .:/four
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    image: backend_celery_flower
    command: /start-flower.sh
    volumes:
      - .:/four
    env_file:
      - ./.env/.dev-sample
    ports: 
      - 5557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres4_data: